- src/App.scss
This fixes a one-off offset on the input completion.
> fix: fix input completion offset

- README.md
We use `yarn` before `npm` in all the other console snippets.
> docs: update export command order

- src/App.js
- src/components/Hits.js
- src/components/Pagination.js
- src/components/Search.js
This scrolls to top on each page change, which avoids users to scroll back to top manually to scan items.
I got rid of the `ScrollTo` component which didn't behave properly, and implemented our own `Pagination` component.
> feat(pagination): scroll to top on page change

- src/App.js
When hitting <kbd>Esc</kbd> with the filters panel open, the whole search experience closed, which was confusing. We now support <kbd>Esc</kbd> to close the filters panel if open, and to close the search experience otherwise.
> feat: allow escape to close filters

- public/index.ejs
- webpack/plugins/files.js
This adds a `preconnect` link to the preview website, interpolated with the `appId` from the configuration.
> feat: add preconnect link to preview website

- src/components/SearchBox/SearchBox.js
Since we switched from React to Preact, the app lost the "autofocus" feature on the input when the modal opens.
This happens because [Preact follows the HTML spec](https://github.com/preactjs/preact/issues/1255#issuecomment-439714572) of triggering the autofocus on page load, and not when the component mounts. React is more aggressive about this behavior.
This therefore gets rid of the `autoFocus` prop which is ignored here, and focuses the input with an effect.
Closes #119.
> fix(searchBox): autofocus input when modal opens

- src/App.scss
- src/components/CurrentRefinements.js
- src/components/CurrentRefinements.scss
- src/components/FiltersButton.js
- src/components/Panel.scss
- src/components/Search.js
This PR changes the following on mobile:
- Move the current refinements in the filters panel
- Display the filters count in the filters button. This gives a clue to users about why only some search results appear.
> feat(mobile): display current refinements in filters panel

- package.json
- webpack/dev.babel.js
This exposes the app to `0.0.0.0` in dev to be able to try the app on mobile on your local network.
I removed the `open` config because (1) it opens it on `0.0.0.0:3000` which displays a "Not secure" message and (2) I find it annoying that it messes up my tabs and virtual desktops.
> chore(webpack): support local network development

- CHANGELOG.md
- package.json
- ship.config.js
- src/version.js
It seems that CircleCI [can't commit](https://circleci.com/gh/algolia/unified-instantsearch-ecommerce/122) because it doesn't have an identity set up (despite the GitHub token).
This PR sets an identity before committing, using Ship.js' [` beforeCommitChanges`](https://community.algolia.com/shipjs/reference/all-config.html#beforecommitchanges) hook.
The solution was suggested by this CircleCI's support center post: https://support.circleci.com/hc/en-us/articles/360018860473-How-to-push-a-commit-back-to-the-same-repository-as-part-of-the-CircleCI-job
> ci: set Git identity before committing

- .circleci/config.yml
- ship.config.js
After discussing with @eunjae-lee it seems that [`beforeCommitChanges`](https://community.algolia.com/shipjs/reference/all-config.html#beforecommitchanges) is for `shipjs prepare`, not `shipjs trigger`. Therefore, we can't use it to set Git identity during the build.
This sets it up right before `shipjs trigger`.
> ci: use CircleCI's config to set Git identity

- src/App.scss
- src/components/Panel.scss
- src/components/ResetButton.js
- src/components/Search.js
This brings the mobile filters panel design closer to what you would expect on a native app:
- Use a cross to close the panel
- Fix spacing (more compact globally, except touchable zones)
- Add shadow to refinement footer
- Rename "Reset filters" to "Clear all"
> fix(mobile): update filters panel design

- src/config/Hit.js
We currently use a **Like** button as the trigger for sending Insights events, but this goes against what we recommend for `convertedObjectIDsAfterSearch`.
In e-commerce, we advise customers to use **Add to cart** as a conversion event rather than **Like**, so even though this is only an example here, having this by default encourages following our best practices.
> feat: replace insights trigger

- package.json
- webpack/dev.babel.js
- yarn.lock
We've seen from user testing that users are surprised and lost with the `webpack-dashboard` output. Additionally, when the process takes time (e.g., slow machine), it showcases the boxes but there's no content and it feels buggy.
I've looked for other reporters but unfortunately I couldn't find any for `webpack-dev-sever`. Therefore, I think it's best to remove it and go back to the default output.
> feat: remove webpack-dashboard

- src/components/SearchButton.js
We generate the search box for users, but it's likely that they will try to integrate Unified in a website that already has one and will try to hook `inputContainer` to it. We mention it in the documentation, but we can't rely on this alone, as this is a likely error and it will make Unified fail from the very first try, causing a pretty bad experience.
We've seen that error during user testing, and it results in Preact throwing way too deep for the error to be understandable. This PR introduces a custom error that makes it clear what is happening and what steps to take from there.
> feat: throw when `inputContainer` refers to an <input>

- src/components/Search.js
- src/config/index.js
Currently, we're repeating the default index name twice in the config file: under `index.indexName` and under `sorts` as the first (default) sort-by option. We can remove this and instead reuse `index.indexName` within the `Search` component.
Note that I didn't keep the default label in the configuration to avoid making it more complex than it needs to be. In case users need to change it (which is possible but probably won't happen that much), they can search it through the project and change it without much trouble.
I've also changed the condition for displaying the sorts (more than one vs. more than none) because we don't need to show the widget if we only have the default sorting.
> feat: reuse config index name as default sort option

- .babelrc
- package.json
- src/components/CurrentRefinements.js
- src/components/Refinements.js
- src/components/SearchButton.js
- src/config/index.js
- src/config/rules.js
- src/index.js
- src/utils/index.js
- webpack/base.babel.js
- webpack/build.babel.js
- webpack/dev.babel.js
- webpack/preview.babel.js
- yarn.lock
In #138 we brought up the idea of [adding a runtime validation step](https://github.com/algolia/unified-instantsearch-ecommerce/pull/138#issuecomment-662900321) to verify invariants. This PR introduces one using [`invariant`](https://github.com/zertosh/invariant), a mirror of what Facebook uses within React.
_**N.B.:** [The React invariant module has changed since then](https://reactjs.org/blog/2016/07/11/introducing-reacts-error-code-system.html), they also provide links to an error decoder on their site which returns the actual invariant message. I think we're okay with the generic message for now since we don't have that many invariants. We can look into it later on if we think this is an actual problem._
Instead of throwing within components when a configuration option isn't properly …
> feat: runtime validation

- postcss.config.js
When a user uses `window` in the config file outside of a function, it will break the `export` process because the `postcss.config.js` file imports the config file to get the data under `styles`. Because `window` doesn't exist in Node, it throws.
This PR fixes the issue by defining `window` and setting it to `global`. We don't care that `window` doesn't exist in that case because we don't want to get data from it in this context. Styles need to be defined statically for now, because we need them to write the stylesheet.
> fix: define `window` to avoid breakage when using it in the config file

- src/components/Search.js
This PR hides the left panel and the filters button on mobile whenever `config.refinements` is empty.
> feat: no refinements layout

- postcss.config.js
When the configuration file refers to `window`, we need to shim it so it doesn't break when processed with Node during the build step. This is a violation of ESLint rules because we shall not assign to native objects or read-only global variables, but it's okay in our case.
Depending on what browsers we decide to support in the future, we may want to leverage [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) instead. We currently cannot since we support IE11, but since Microsoft has decided to drop support, and depending on InstantSearch decisions regarding browser support, we may want to follow that as well.
> fix: authorize global assignment of `window` in PostCSS file

- src/config/settings.js
The `searchable` option is not supported by [`HierarchicalMenu`](https://www.algolia.com/doc/api-reference/widgets/hierarchical-menu/react/).
> fix(settings): remove unsupported `searchable` hierarchical option

- .circleci/config.yml
- package.json
- ship.config.js
- yarn.lock
This updates our broken releasing process. The new flow is:
- Trigger `yarn release`
- Opens a PR via Ship.js targeting the `next` branch
- We squash merge the PR
- Ship.js prepares the release and runs the command `git checkout master && git rebase next` to get all the commits from `next` to `master`
> chore(release): fix release process

- webpack/base.babel.js
This PR removes `react-router` and `react-router-dom` from the transpilation exclusion list, as in they are exported in ES6, which breaks compatibility with IE11.
> fix: include react-router in transpilation to es5
